apiVersion: batch/v1
kind: CronJob
metadata:
  name: sportsodds-fetch
  namespace: sportsodds
spec:
  schedule: "0 */12 * * *"
  startingDeadlineSeconds: 600
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 300
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: sportsodds-fetch
              image: 897722678706.dkr.ecr.ap-southeast-2.amazonaws.com/sportsodds:887543f8
              command: ["node", "cronFetch.js"]
              env:
                - name: NODE_TLS_REJECT_UNAUTHORIZED
                  value: "0"
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: sportsodds-pg-app
                      key: uri
              envFrom:
                - secretRef:
                    name: sportsodds-secrets
              resources:
                requests: { cpu: 50m, memory: 128Mi }
                limits:   { cpu: 300m, memory: 256Mi }